apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-lb
spec:
  type: NodePort
  ports:
  - nodePort: 32327
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-web-app