apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
  labels:
    app: sa-web-app
spec:
  selector:
    matchLabels:
      app: sa-web-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
      - image: "{{ .Values.image.backendRepository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://34.210.42.162:31816"
        ports:
          - containerPort: 8080